// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgechlpgjiwinvhkwelo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnZWNobHBnaml3aW52aGt3ZWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDIzNDksImV4cCI6MjA2NjE3ODM0OX0.tB-icsIqqVDtLC8bYqv6B54rBZpP80yleEbFmsUtOlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);